name: 'Update Release Artifact'
description: 'Updates the release artifact based on the supplied workflow artifact'
inputs:
  artifact_path:
    required: true
  release_id:
    required: true
  GITHUB_TOKEN:
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
